[ui]
hideTopBar = true

[browser]
gatherUsageStats = false

[server]
fileWatcherType = "none"
port = 8501

[theme]
primaryColor="#E40EAB" # purple
backgroundColor="#000A32"
secondaryBackgroundColor="#000E47"
textColor="#FFFFFF"
font="sans serif"
